version: "3"

services:
  back:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - pgdb
    networks:
      - mynet

  pgdb:
    image: postgres
    ports:
      - "8001:5432"
    networks:
      - mynet

# Add Network to be able to establish connection between bask and DB
networks:
    mynet:
      driver: bridge