version: '2'
services:
  back:
    build: .
    ports:
      - "9000:9000"
    links:
      - mongo:mongo
    depends_on:
      - mongo

  mongo:
    image: ehayanis/mongo
    ports:
      - "28017:28017"
      - "27017:27017"
    volumes:
      - /private/var/data:/data/db