version: '2'
services:
  back:
    build: .
    ports:
      - "9000:9000"
    links:
      - db-service:db-service
    depends_on:
      - db-service

  db-service:
    image: postgres
    ports:
      - "5433:5432"