apiVersion: v1
kind: ReplicationController
metadata:
  name: backapp-deployment

spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image:
          name:
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 80
              hostPort: 80
              containerPort: 443
              hostPort: 443
