---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-deployment

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: data-volume
          hostPath:
            path: /private/var/data
      containers:
        - name: mongo
          image: ehayanis/mongo
          #volumeMounth:
          #  - mounthPath: /mongo
          #    name: data-volume
          ports:
            - name: mongo-port
              containerPort: 27017

